# Generated by Django 5.1.1 on 2024-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ART', 'Artisan'), ('AGR', 'Agriculture')]),
        ),
    ]
